### PR TITLE
107246572 cheetahmail encoding

### PR DESCRIPTION
**Pull request by bsimpson**
https://www.pivotaltracker.com/story/show/107246572

### CODE REVIEW

**Comment by rstawarz** [comment]
:spades: LGTM 

FWIW - you'll probably want to test this locally with Bespoke before going through the trouble to merge this IMO

**Comment by bsimpson** [comment]
@rstawarz Good idea. I updated the `cheetah_mailer.yml` with the settings for staging copied to development. and my Gemfile entry for cheetah pointed to my local path. Then I tested in a Rails console with:

```
cheetah = Cheetah::Cheetah.new({
      :host             => 'ebm.cheetahmail.com',
      :username         => 'bespokeoffers_api',
      :password         => 'Xc72Y9q3Hj',
      :aid              => '2092621312',
      :whitelist_filter => //,
      :enable_send_not_deployed   => false,
      :messenger        => Cheetah::ResqueMessenger
    })

cheetah.send_email(221531, 'ben.simpson@digitaloffersengineering.com', { REASON_FOR_ENQUIRY: "this is a test £100.00" })
```

And received the following:

screen shot 2015-11-02 at 5 26 14 pm

**Comment by bsimpson** [comment]
Not thrilled with the Â prefixing the special character, but I think we would have to alter encoding on both ends to ISO 8859-1. This feels like it would take a while

**Comment by bsimpson** [comment]
I've updated the Gemfile reference in MP. I didn't think it warranted a separate PR

**Pull request merged**
